plugin: community.general.proxmox
url: https://192.168.1.96:8006/
user: "tf@pve"
token_id: "tf-token"
token_secret: "{{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"
validate_certs: false
want_facts: true
want_proxmox_nodes_ansible_host: true
compose:
  ansible_host: proxmox_agent_interfaces[1]["ip-addresses"][0].split('/')[0]
keyed_groups:
  - key: proxmox_tags_parsed
    separator: ""
groups:
  ubuntu_servers: "'ubuntu' in (proxmox_tags_parsed|list)"

ansible_ssh_private_key_file: /root/.ssh/id_ed25519.pub

