---
- name: Install Pihole
  hosts: env_lab
  become: true
  gather_facts: true

  vars:
    # Change upstreams / options to your taste
    pihole_dns_1: "9.9.9.9"
    pihole_dns_2: "149.112.112.112"
    install_web:  true        # false if you bring your own web server
    skip_os_check: true       # set false if your OS is officially supported
    # leave empty to let Pi-hole generate one; or put double-SHA256 hash
    webpassword_hash: ""      

  tasks:
    - name: Ensure config dirs exist
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - /etc/pihole
        - /etc/dnsmasq.d

    - name: Build IPv4/CIDR string (e.g. 192.168.1.10/24)
      set_fact:
        pihole_ipv4_cidr: "{{ ansible_default_ipv4.address }}/{{ ansible_default_ipv4.netmask | ipaddr('prefix') }}"
        pihole_iface: "{{ ansible_default_ipv4.interface }}"

    - name: Write /etc/pihole/setupVars.conf
      copy:
        dest: /etc/pihole/setupVars.conf
        mode: "0644"
        content: |
          WEBPASSWORD={{ webpassword_hash }}
          PIHOLE_INTERFACE={{ pihole_iface }}
          IPV4_ADDRESS={{ pihole_ipv4_cidr }}
          IPV6_ADDRESS=
          QUERY_LOGGING=true
          INSTALL_WEB_INTERFACE={{ 'true' if install_web else 'false' }}
          INSTALL_WEB_SERVER={{ 'true' if install_web else 'false' }}
          LIGHTTPD_ENABLED={{ 'true' if install_web else 'false' }}
          DNSMASQ_LISTENING=single
          PIHOLE_DNS_1={{ pihole_dns_1 }}
          PIHOLE_DNS_2={{ pihole_dns_2 }}
          DNS_FQDN_REQUIRED=true
          DNS_BOGUS_PRIV=true
          DNSSEC=false
          TEMPERATUREUNIT=C
          WEBUIBOXEDLAYOUT=traditional
          API_QUERY_LOG_SHOW=all
          API_PRIVACY_MODE=false
          BLOCKING_ENABLED=true
      register: setupvars

    - name: Check if Pi-hole is installed
      stat:
        path: /usr/local/bin/pihole
      register: pihole_bin

    - name: Install/repair Pi-hole unattended
      shell: |
        {{ 'PIHOLE_SKIP_OS_CHECK=true ' if skip_os_check else '' }} \
        curl -L https://install.pi-hole.net | bash /dev/stdin --unattended {{ '--disable-install-webserver' if not install_web else '' }}
      args:
        executable: /bin/bash
      when: not pihole_bin.stat.exists or setupvars.changed
